check for PTHREAD_MUTEX_RECURSIVE in configure instead of with #ifdef (enum is used on freebsd)
r4462

diff --git a/FreeBASIC/src/rtlib/configure b/FreeBASIC/src/rtlib/configure
--- a/FreeBASIC/src/rtlib/configure
+++ b/FreeBASIC/src/rtlib/configure
@@ -5316,6 +5316,76 @@ _ACEOF
 fi
 
 
+# Checks for declarations.
+echo "$as_me:$LINENO: checking whether PTHREAD_MUTEX_RECURSIVE is declared" >&5
+echo $ECHO_N "checking whether PTHREAD_MUTEX_RECURSIVE is declared... $ECHO_C" >&6
+if test "${ac_cv_have_decl_PTHREAD_MUTEX_RECURSIVE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <pthread.h>
+
+int
+main ()
+{
+#ifndef PTHREAD_MUTEX_RECURSIVE
+  char *p = (char *) PTHREAD_MUTEX_RECURSIVE;
+#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_have_decl_PTHREAD_MUTEX_RECURSIVE=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_have_decl_PTHREAD_MUTEX_RECURSIVE=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_have_decl_PTHREAD_MUTEX_RECURSIVE" >&5
+echo "${ECHO_T}$ac_cv_have_decl_PTHREAD_MUTEX_RECURSIVE" >&6
+if test $ac_cv_have_decl_PTHREAD_MUTEX_RECURSIVE = yes; then
+  have_pthread_mutex_recursive=1
+fi
+
+
+if test "$have_pthread_mutex_recursive" != "1"; then
+    cat >>confdefs.h <<\_ACEOF
+#define PTHREAD_MUTEX_RECURSIVE PTHREAD_MUTEX_RECURSIVE_NP
+_ACEOF
+
+fi
+
 # Checks for library functions.
 # The Ultrix 4.2 mips builtin alloca declared by alloca.h only works
 # for constant arguments.  Useless!
