move architecture-specific code to its own directory
r3221

diff --git a/FreeBASIC/src/rtlib/configure b/FreeBASIC/src/rtlib/configure
--- a/FreeBASIC/src/rtlib/configure
+++ b/FreeBASIC/src/rtlib/configure
@@ -313,7 +313,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os FBRT_TARGET SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP RANLIB ac_ct_RANLIB ACLOCAL AUTOCONF AUTOHEADER ALLOCA LIBOBJS POW_LIB MAINT LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os FBRT_TARGET FBRT_CPU SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP RANLIB ac_ct_RANLIB ACLOCAL AUTOCONF AUTOHEADER ALLOCA LIBOBJS POW_LIB MAINT LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1489,8 +1489,15 @@ cat >>confdefs.h <<\_ACEOF
 #define TARGET_X86 1
 _ACEOF
 
+		FBRT_CPU=x86;;
+	*)
+		{ { echo "$as_me:$LINENO: error: Unsupported CPU" >&5
+echo "$as_me: error: Unsupported CPU" >&2;}
+   { (exit 1); exit 1; }; }
 		;;
 esac
+
+
 
 # Checks for programs.
 echo "$as_me:$LINENO: checking whether ${MAKE-make} sets \$(MAKE)" >&5
@@ -7969,6 +7976,7 @@ s,@target_cpu@,$target_cpu,;t t
 s,@target_vendor@,$target_vendor,;t t
 s,@target_os@,$target_os,;t t
 s,@FBRT_TARGET@,$FBRT_TARGET,;t t
+s,@FBRT_CPU@,$FBRT_CPU,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
 s,@CC@,$CC,;t t
 s,@CFLAGS@,$CFLAGS,;t t
